### ISSUE TITLE
Erlang package has bad symlink to for erl

### ISSUE THREAD

**Issue by clintoncwolfe** [omniti-labs/omniti-ms#2]
erl, one of the main binaries of the erlang package, is packaged as a symlink:

```
/opt/omni/bin/erl -> ../../lib/amd64/erlang/bin/erl
```

which resolves to /opt/lib/amd64/erlang/bin/erl , which does not exist.   This breaks most erlang code.  opt/omni/lib/amd64/erlang/bin/erl does exist, however, and removing the extra .. fixed the issue.

Observed in ms.omniti.com/omniti/runtime/erlang pkg:/omniti/runtime/erlang@18.3.0-0.151014

**Comment by danmcd** [comment]
This is a problem with the building scripts that can't handle Erlang's installation of a symlink.  Here's a slack conversation (internal only) covering it:

https://omniti.slack.com/archives/omnios/p1471288037001135

**Comment by mamurphy** [comment]
This commit should fix future builds of erlang until we reevaluate functions.sh:
https://github.com/omniti-labs/omniti-ms/commit/36af8b4076a7afea5478b88b99e47a04e4e29965

A new erlang@18.3 package has been published.

```
mmurphy@zone:~$ pkg info erlang | grep FMRI
          FMRI: pkg://ms.omniti.com/omniti/runtime/erlang@18.3.0-0.151014:20160819T184735Z
mmurphy@zone:~$ /opt/omni/bin/erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1>
```
